plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-2.1.1.cjs

##pnpMode: "loose"
#packageExtensions:
#  "fork-ts-checker-webpack-plugin@*":
#    peerDependencies:
#      "typescript": "*"
#      "webpack": "*"
#  "@types/fork-ts-checker-webpack-plugin@*":
#    peerDependencies:
#      "@types/typescript": "*"
#      "@types/webpack": "*"
#  "webpack@*":
#    peerDependencies:
#      "webpack-cli":
#        optional: true
#  "webpack-cli@*":
#    peerDependencies:
#      "ts-node":
#        optional: true
nodeLinker: node-modules