AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

#Metadata:
#  AWS::ServerlessRepo::Application:
#    Name: CryptoExchangeRates
#    Description: A simple PUT-GET Framework
#    Author: Tyler Reid
#    LicenseUrl: LICENSE
#    ReadmeUrl: README.md
#    Labels: ['some-label']
#    HomePageUrl: https://github.com
#    SemanticVersion: 0.0.1
#    SourceCodeUrl: https://github.com

Parameters:
  ProjectId:
    Type: String
    Description: AWS CodeStar projectID used to associate new resources to team members
  CodeDeployRole:
    Type: String
    Description: IAM role to allow AWS CodeDeploy to manage deployment of AWS Lambda functions
  Stage:
    Type: String
    Description: The name for a project pipeline stage, such as Staging or Prod, for which resources are provisioned and deployed.
    Default: ''
  Application:
    Type: String
    Default: ''
  TableName:
    Type: String
    Description: Table Name for DynamoDb Exchange Rates Table

Globals:
  Function:
    AutoPublishAlias: live
    DeploymentPreference:
      Enabled: true
      Type: Canary10Percent5Minutes
      Role: !Ref CodeDeployRole

Resources:
  CryptocurrencyRateController:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${Application}-${ProjectId}-CryptocurrencyRateController-${Stage}'
      Handler: index.handler
      Runtime: nodejs12.x
      Environment:
        Variables:
          NODE_ENV: !Sub '${Stage}'
      Role:
        Fn::GetAtt:
        - LambdaInvocationRole
        - Arn
      Events:
        GetRate:
          Type: Api
          Properties:
            Path: /exchangerate/{baseCurr}/{date}/{quoteCurr}
            Method: GET
        ListRates:
          Type: Api
          Properties:
            Path: /exchangerate/list
            Method: GET
        UploadRates:
          Type: Api
          Properties:
            Path: /exchangerate
            Method: POST
      Timeout: 3
      CodeUri: src/cryptocurrency-rate-controller
  FindCryptocurrencyRate:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${Application}-${ProjectId}-FindCryptocurrencyRate-${Stage}'
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: src/find-cryptocurrency-rate
      Environment:
        Variables:
          NODE_ENV: !Sub ${Stage}
          DYNAMODB_TABLE: !Sub ${DYNAMODB_TABLE}
          DYNAMODB_ENDPOINT: !Sub ${DYNAMODB_ENDPOINT}
          IS_OFFLINE: !Sub ${IS_OFFLINE}
      MemorySize: 128
      Timeout: 3
      Role:
        Fn::GetAtt:
          - LambdaInvocationRole
          - Arn
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TableName
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:
        Ref: TableName
      AttributeDefinitions:
        - AttributeName:
            Fn::Sub: ${TableName}Id
          AttributeType: S
      KeySchema:
        - AttributeName:
            Fn::Sub: ${TableName}Id
          KeyType: HASH
      SSESpecification:
        SSEEnabled: true
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      BillingMode: PAY_PER_REQUEST
  LambdaInvocationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${Application}-${ProjectId}-LambdaInvocationRole-${Stage}'
      AssumeRolePolicyDocument:
        Statement:
          - 
            Effect: Allow
            Principal: 
              Service: 
                - lambda.amazonaws.com
            Action: 
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/service-role/lts -'
      PermissionsBoundary: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/CodeStar_${ProjectId}_PermissionsBoundary'



