AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar
 # https://github.com/aws/serverless-application-model/blob/develop/versions/2016-10-31.md
#Metadata:
#  AWS::ServerlessRepo::Application:
#    Name: CryptoExchangeRates
#    Description: A simple PUT-GET Framework
#    Author: Tyler Reid
#    LicenseUrl: LICENSE
#    ReadmeUrl: README.md
#    Labels: ['some-label']
#    HomePageUrl: https://github.com
#    SemanticVersion: 0.0.1
#    SourceCodeUrl: https://github.com
# s3 sfw-deploy-ufddzmpkg

Parameters:
  ProjectId:
    Type: String
    Default: 'ezs'
    Description: AWS CodeStar projectID used to associate new resources to team members
  Application:
    Type: String
    Default: 'EZSam'
    Description: The application name
  CodeDeployRole:
    Type: String
    Description: IAM role to allow AWS CodeDeploy to manage deployment of AWS Lambda functions
  Stage:
    Type: String
    Default: Prod
    AllowedValues:
      - Dev
      - Test
      - Prod
    Description: The name for a project pipeline stage, such as Dev, Test, or Prod for which resources are provisioned and deployed.
    ConstraintDescription: Only Dev, Test, or Prod allowed
  CloudWatchRetentionInDays:
    Type: Number
    Default: 7
    Description: Number of days to retain this stage's logs
  BucketName:
    Type: String
    Default: ''
    Description: Bucket Name for S3
  TableName:
    Type: String
    Description: Table Name for DynamoDB Table
  TableEndpoint:
    Type: String
    Default: ''
  FunctionEndpoint:
    Type: String
    Default: ''

Conditions:
  IsOffline: !Equals [!Ref Stage, Dev]

Globals:
  Function:
    AutoPublishAlias: live
    DeploymentPreference:
      Enabled: true
      Type: Canary10Percent5Minutes
      Role: !Ref CodeDeployRole
      Tags:
        StageName: !Sub ${Stage}
        Application: !Sub ${Application}

Resources:
  TranslationHttpApi:
    Type: AWS::Serverless::HttpApi # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-httpapi.html
    Properties:
      AccessLogSettings:
        DestinationArn: !GetAtt CloudWatchLogApiGateway.Arn
        Format: >-
          {"requestId":"$context.requestId", "ip": "$context.identity.sourceIp",
          "caller":"$context.identity.caller",
          "user":"$context.identity.user","requestTime":"$context.requestTime",
          "eventType":"$context.eventType","routeKey":"$context.routeKey",
          "status":"$context.status","connectionId":"$context.connectionId"}
        # Auth: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-httpapi-httpapiauth.html
        CorsConfiguration: true
        DefaultRouteSettings:
          DataTraceEnabled: false
          DetailedMetricsEnabled: false
          LoggingLevel: OFF
#          ThrottlingBurstLimit: Integer
#          ThrottlingRateLimit: Double
        DefinitionBody:
          Fn::Transform:
            Name: AWS::Include
            Parameters:
              Location: resources/open-api.yaml
#        DefinitionUri: String | HttpApiDefinition
        Description: Translation Api
        StageName: !Sub ${Stage}
        StageVariables: Json
        Tags: Map

#  SpeechBucket:
#    Type: AWS::S3::Bucket
#    Properties:
#      BucketName: !Sub !{BucketName}

  GetTranslationController:
    Type: AWS::Serverless::Function # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
    Properties:
      FunctionName: !Sub '${Application}-${ProjectId}-GetTranslationController-${Stage}'
      Description: Get translation
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: src/get-translation-controller
      #      DeadLetterQueue:
      #        Type: SNS
      #        TargetArn: arn:aws:sns:us-east-2:123456789012:my-topic
      Environment:
        Variables:
          STAGE: !Sub ${Stage}
          IS_OFFLINE: !Equals [ IsOffline, true ]
          REPOSITORY_SERVICE_FUNCTION: !Ref RepositoryService
          FUNCTION_ENDPOINT: !Sub ${FunctionEndpoint}
      Events:
        GetTranslation:
          Type: HttpApi
          Properties:
            ApiId: !Ref TranslationHttpApi
            Method: GET
            PayloadFormatVersion: "2.0"
            Path: /v1/translation/{source}/{target}/{word}
      MemorySize: 128
      Role: !GetAtt LambdaInvocationRole.Arn
      Timeout: 3
      Tags:
        StageName: !Sub ${Stage}
        Application: !Sub ${Application}

  UploadTranslationController:
    Type: AWS::Serverless::Function # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
    Properties:
      FunctionName: !Sub '${Application}-${ProjectId}-UploadTranslationController-${Stage}'
      Description: Upload translations
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: src/upload-translation-controller
#      DeadLetterQueue:
#        Type: SNS
#        TargetArn: arn:aws:sns:us-east-2:123456789012:my-topic
      Environment:
        Variables:
          STAGE: !Sub ${Stage}
          REPOSITORY_SERVICE_FUNCTION: !Ref RepositoryService
          POLLY_SYNTHESIZER_FUNCTION: !Ref PollySynthesizer
          FUNCTION_ENDPOINT: !Sub ${FunctionEndpoint}
          IS_OFFLINE: !Equals [IsOffline, true]
      Events:
        UploadTranslations:
          Type: HttpApi
          Properties:
            ApiId: !Ref TranslationHttpApi
            Method: POST
            PayloadFormatVersion: "2.0"
            Path: /v1/translation
      MemorySize: 128
      Role: !GetAtt LambdaInvocationRole.Arn
      Timeout: 3
      Tags:
        StageName: !Sub ${Stage}
        Application: !Sub ${Application}

  RepositoryService:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${Application}-${ProjectId}-RepositoryService-${Stage}'
      Description: CRUD
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: src/repository-service
      Environment:
        Variables:
          STAGE: !Sub ${Stage}
          DYNAMODB_TABLE: !Sub ${TableName}
          DYNAMODB_ENDPOINT: !Sub ${TableEndpoint}
          IS_OFFLINE: !If [ IsOffline, true, false ]
      MemorySize: 128
      Role: !GetAtt LambdaInvocationRole.Arn
      Timeout: 3
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TableName
      Tags:
        StageName: !Sub ${Stage}
        Application: !Sub ${Application}

  PollySynthesizer:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${Application}-${ProjectId}-PollySynthesizer-${Stage}'
      Description: Synthesizes text to Speech
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: src/polly-synthezier
      Environment:
        Variables:
          STAGE: !Sub ${Stage}
          REPOSITORY_SERVICE_FUNCTION: !Ref RepositoryService
          FUNCTION_ENDPOINT: !Sub ${FunctionEndpoint}
          IS_OFFLINE: !If [IsOffline, true, false]
      MemorySize: 128
      Role: !GetAtt LambdaInvocationRole.Arn
      Timeout: 3
      Policies:
        - S3CrudPolicy:
            TableName: !Ref SpeechBucket
        - PollyFullAccessPolicy: {}
      Tags:
        StageName: !Sub ${Stage}
        Application: !Sub ${Application}

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      AttributeDefinitions:
        - AttributeName:
            Fn::Sub: ${TableName}
          AttributeType: S
      KeySchema:
        - AttributeName:
            Fn::Sub: ${TableName}
          KeyType: HASH
      SSESpecification:
        SSEEnabled: true
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: StageName
          Value: !Sub ${Stage}
        - Key: Application
          Value: !Sub ${Application}

  CloudWatchLogGetTranslationController:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: !Sub {CloudWatchRetentionInDays}
      LogGroupName: !Sub /aws/lambda/${GetTranslationController}

  CloudWatchLogUploadTranslationController:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: !Sub {CloudWatchRetentionInDays}
      LogGroupName: !Sub /aws/lambda/${UploadTranslationController}

  CloudWatchLogRepositoryService:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: !Sub {CloudWatchRetentionInDays}
      LogGroupName: !Sub /aws/lambda/${RepositoryService}

  CloudWatchLogPollySynthesizer:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 7
      LogGroupName: !Sub /aws/lambda/${PollySynthesizer}

  CloudWatchLogApiGateway:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: !Sub {CloudWatchRetentionInDays}
      LogGroupName: !Sub /aws/apigateway/${ApiGatewayApi.arn}

  LambdaInvocationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${Application}-${ProjectId}-LambdaInvocationRole-${Stage}'
      AssumeRolePolicyDocument:
        Statement:
          - 
            Effect: Allow
            Principal: 
              Service: 
                - lambda.amazonaws.com
            Action: 
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - !Sub 'arn:aws:iam::aws:policy/CloudWatchFullAccess'
        - !Sub 'arn:aws:iam::aws:policy/AWSLambda_FullAccess'
      Tags:
        - Key: StageName
          Value: !Sub ${Stage}
        - Key: Application
          Value: !Sub ${Application}



#Fn::!Equals:
#  - !Equals [IsOffline, true]
#  -
#    Outputs:
#      TranslationHttpApi:
#        Description: API Gateway endpoint URL for Prod stage for Hello World function
#        Value:
#          Fn::Sub: https://${TranslationHttpApi}.execute-api.${AWS::Region}.amazonaws.com/
#      ExpressBackendFunction:
#        Description: Express Backend Lambda Function ARN
#        Value: !Sub TranslationController.Arn