openapi: 3.0.0
info: #https://mechanicalrock.github.io/2020/01/27/serverless-express-openapi.html
  title: EZS API
  description: A simple API for uploading and retrieving a word's translation
  version: "1.0"
paths:
#  /translation:
#    post:
#      operationId: UploadTranslations
#      requestBody:
#        content:
#          application/json:
#            schema:
#              $ref: "#/components/schemas/ExchangeRateItem"
#        required: true
#      responses:
#        "200":
#          description: "Successfully uploaded exchange rates."
#          content:
#            application/json:
#              schema:
#                $ref: "#/components/schemas/UploadTranslationsResponse"

  /translation/{source}/{target}/{word}:
    get:
      operationId: GetTranslation
      parameters:
        - name: source
          in: query
          required: true
          schema:
            type: string
        - name: target
          in: query
          required: true
          schema:
            type: string
        - name: word
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Successfully retrieved translation."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetTranslationResponse"

#  /v1/translation/list:
#    get:
#      operationId: ListTranslations
#      responses:
#        "200":
#          description: "Successfully retrieved translation list."
#          headers:
#            "X-DNS-Prefetch-Control": "off",
#            "Strict-Transport-Security": "max-age=15552000; includeSubDomains; preload",
#            "X-Download-Options": "noopen",
#            "X-Content-Type-Options": "nosniff",
#            "Referrer-Policy": "no-referrer",
#            "X-Permitted-Cross-Domain-Policies": "none"
#          content:
#            application/json:
#              schema:
#                $ref: "#/components/schemas/ListTranslationsResponse"

#        "400":
#          description: "Bad Request Exception"
#          content:
#            application/json:
#              schema:
#                $ref: "#/components/schemas/BadRequestException"
#        "500":
#          description: "Internal Server Error"
#          content:
#            application/json:
#              schema:
#                $ref: "#/components/schemas/InternalServerErrorException"
components:
  schemas:
    TranslationItem:
      type: object
      properties:
        source:
          type: string
        target:
          type: string
        word:
          type: string

    GetTranslationResponse:
      type: object
      properties:
        ExchangeRateItem:
          $ref: "#/components/schemas/TranslationItem"

    ListTranslationsResponse:
      type: object
      properties:
        payload:
          type: object
          properties:
            Items:
              type: array
              properties:
                Items:
                  $ref: "#/components/schemas/Translation"

    UploadTranslation:
      type: array
      properties:
        language:
          type: string
        source:
          type: string
        target:
          type: string
        definition:
          type: string

    UploadExchangeRatesResponse:
      type: object
      properties:
        payload:
          type: object
          properties:
            UnprocessedItems:
              type: object