AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ProjectId:
    Type: String
    Default: sfw
    Description: AWS CodeStar projectID used to associate new resources to team members
  Application:
    Type: String
    Default: EZSam
    Description: The application name
  Stage:
    Type: String
    Default: Prod
    AllowedValues:
      - Dev
      - Test
      - Prod
    Description: The name for a project pipeline stage, such as Dev, Test, or Prod for which resources are provisioned and deployed.
    ConstraintDescription: Only Dev, Test, or Prod allowed
  TableName:
    Type: String
    Description: Table Name for DynamoDB Table

Resources:
  MediaBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${MediaBucketName}
#    Type: AWS::S3::BucketPolicy
#    Properties:
#      Bucket: String
#      PolicyDocument: Json