version: '3'
services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    hostname: dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8042:8000"
    command:  ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]
